// Generated by CoffeeScript 1.3.3
(function() {
  var Agent;

  Agent = (function() {

    function Agent(teamSize, homebase, id) {
      this.teamSize = teamSize;
      this.homebase = homebase;
      this.id = id;
    }

    Agent.prototype.newSurrounding = function(surrounding) {};

    Agent.prototype.chooseAction = function() {
      return "pass";
    };

    Agent.prototype.getMoveDirection = function() {
      return "N";
    };

    Agent.prototype.newPosition = function(newPos) {};

    Agent.prototype.pointCollected = function() {};

    Agent.prototype.pointNotCollected = function() {};

    Agent.prototype.pointScored = function() {};

    Agent.prototype.getMessage = function() {
      return "";
    };

    Agent.prototype.receiveMessage = function(msg) {};

    Agent.prototype.getName = function() {
      if (this.id != null) {
        return this.id;
      } else {
        return "";
      }
    };

    Agent.prototype.say = function(text) {
      var msg;
      msg = "";
      if (this.id != null) {
        msg = "" + this.id + ": ";
      }
      msg += text;
      return console.log(msg);
    };

    Agent.prototype.toString = function() {
      var describtion;
      describtion = "";
      if (this.getTeam != null) {
        describtion += this.getTeam();
      }
      if (this.id != null) {
        describtion += "#" + this.id + " ";
      }
      return describtion;
    };

    return Agent;

  })();

  this.Agent = Agent;

}).call(this);
